// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tozrliwakmncoebhqlof.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRvenJsaXdha21uY29lYmhxbG9mIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg0NjEwODksImV4cCI6MjA3NDAzNzA4OX0.rSsEfvP71XuBaHn_yVbM4zZOob_zEiRqZ_UV14cEGWU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});